"""create configurable action templates

Revision ID: 055f95d420fc
Revises: 0f058599b958
Create Date: 2026-07-14 15:04:49.326219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '055f95d420fc'
down_revision: Union[str, Sequence[str], None] = '0f058599b958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('match_semantic_tags_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('match_needs_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('match_life_domains_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('match_goal_categories_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('match_coping_styles_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('conditions_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('base_priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('base_confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('minimum_score', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_confidence >= 0 AND base_confidence <= 1', name='ck_action_templates_base_confidence_range'),
    sa.CheckConstraint('base_priority >= 1 AND base_priority <= 10', name='ck_action_templates_base_priority_range'),
    sa.CheckConstraint('minimum_score >= 0', name='ck_action_templates_minimum_score'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_templates_code'), 'action_templates', ['code'], unique=True)
    op.create_index(op.f('ix_action_templates_is_active'), 'action_templates', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_templates_is_active'), table_name='action_templates')
    op.drop_index(op.f('ix_action_templates_code'), table_name='action_templates')
    op.drop_table('action_templates')
    # ### end Alembic commands ###
