"""create user coping styles

Revision ID: 09ea06426e1b
Revises: 1662ec251a0c
Create Date: 2026-07-07 13:28:39.249156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09ea06426e1b'
down_revision: Union[str, Sequence[str], None] = '1662ec251a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coping_styles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_coping_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disliked_coping_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('writing_preference_score', sa.SmallInteger(), nullable=False),
    sa.Column('movement_preference_score', sa.SmallInteger(), nullable=False),
    sa.Column('breathing_preference_score', sa.SmallInteger(), nullable=False),
    sa.Column('social_support_preference_score', sa.SmallInteger(), nullable=False),
    sa.Column('reflection_preference_score', sa.SmallInteger(), nullable=False),
    sa.Column('structure_preference_score', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('breathing_preference_score >= 0 AND breathing_preference_score <= 10', name='ck_user_coping_styles_breathing_score_range'),
    sa.CheckConstraint('movement_preference_score >= 0 AND movement_preference_score <= 10', name='ck_user_coping_styles_movement_score_range'),
    sa.CheckConstraint('reflection_preference_score >= 0 AND reflection_preference_score <= 10', name='ck_user_coping_styles_reflection_score_range'),
    sa.CheckConstraint('social_support_preference_score >= 0 AND social_support_preference_score <= 10', name='ck_user_coping_styles_social_support_score_range'),
    sa.CheckConstraint('structure_preference_score >= 0 AND structure_preference_score <= 10', name='ck_user_coping_styles_structure_score_range'),
    sa.CheckConstraint('writing_preference_score >= 0 AND writing_preference_score <= 10', name='ck_user_coping_styles_writing_score_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_coping_styles_created_at'), 'user_coping_styles', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_coping_styles_created_at'), table_name='user_coping_styles')
    op.drop_table('user_coping_styles')
    # ### end Alembic commands ###
