"""extend life events with semantic event fields

Revision ID: 0f058599b958
Revises: 0c51568e5ab6
Create Date: 2026-07-14 13:27:15.506970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f058599b958'
down_revision: Union[str, Sequence[str], None] = '0c51568e5ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('life_events', sa.Column('source_semantic_frame_id', sa.UUID(), nullable=True))
    op.add_column('life_events', sa.Column('significance', sa.Float(), nullable=True))
    op.add_column('life_events', sa.Column('valence', sa.Float(), nullable=True))
    op.add_column('life_events', sa.Column('semantic_tags_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('life_events', sa.Column('life_domains_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.create_index('ix_life_events_life_domains_gin', 'life_events', ['life_domains_json'], unique=False, postgresql_using='gin')
    op.create_index('ix_life_events_semantic_tags_gin', 'life_events', ['semantic_tags_json'], unique=False, postgresql_using='gin')
    op.create_index('ix_life_events_source_semantic_frame_id', 'life_events', ['source_semantic_frame_id'], unique=False)
    op.create_foreign_key(None, 'life_events', 'journal_semantic_frames', ['source_semantic_frame_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'life_events', type_='foreignkey')
    op.drop_index('ix_life_events_source_semantic_frame_id', table_name='life_events')
    op.drop_index('ix_life_events_semantic_tags_gin', table_name='life_events', postgresql_using='gin')
    op.drop_index('ix_life_events_life_domains_gin', table_name='life_events', postgresql_using='gin')
    op.drop_column('life_events', 'life_domains_json')
    op.drop_column('life_events', 'semantic_tags_json')
    op.drop_column('life_events', 'valence')
    op.drop_column('life_events', 'significance')
    op.drop_column('life_events', 'source_semantic_frame_id')
    # ### end Alembic commands ###
