"""create action suggestions

Revision ID: 113701065477
Revises: 25e28797c804
Create Date: 2026-07-05 12:50:09.775100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113701065477'
down_revision: Union[str, Sequence[str], None] = '25e28797c804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_code', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='ck_action_suggestion_priority'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_action_suggestion_confidence_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'action_code', 'source_type', 'source_id', name='uq_action_suggestion_user_action_source')
    )
    op.create_index(op.f('ix_action_suggestions_action_code'), 'action_suggestions', ['action_code'], unique=False)
    op.create_index(op.f('ix_action_suggestions_action_type'), 'action_suggestions', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_suggestions_created_at'), 'action_suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_suggestions_priority'), 'action_suggestions', ['priority'], unique=False)
    op.create_index(op.f('ix_action_suggestions_source_id'), 'action_suggestions', ['source_id'], unique=False)
    op.create_index(op.f('ix_action_suggestions_source_type'), 'action_suggestions', ['source_type'], unique=False)
    op.create_index(op.f('ix_action_suggestions_user_id'), 'action_suggestions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_suggestions_user_id'), table_name='action_suggestions')
    op.drop_index(op.f('ix_action_suggestions_source_type'), table_name='action_suggestions')
    op.drop_index(op.f('ix_action_suggestions_source_id'), table_name='action_suggestions')
    op.drop_index(op.f('ix_action_suggestions_priority'), table_name='action_suggestions')
    op.drop_index(op.f('ix_action_suggestions_created_at'), table_name='action_suggestions')
    op.drop_index(op.f('ix_action_suggestions_action_type'), table_name='action_suggestions')
    op.drop_index(op.f('ix_action_suggestions_action_code'), table_name='action_suggestions')
    op.drop_table('action_suggestions')
    # ### end Alembic commands ###
