"""create user contexts

Revision ID: 1662ec251a0c
Revises: 21aba7c25698
Create Date: 2026-07-07 10:52:41.864094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1662ec251a0c'
down_revision: Union[str, Sequence[str], None] = '21aba7c25698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contexts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age_range_min', sa.Integer(), nullable=False),
    sa.Column('age_range_max', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('work_situation', sa.String(length=50), nullable=False),
    sa.Column('relationship_status', sa.String(length=50), nullable=False),
    sa.Column('family_support_score', sa.SmallInteger(), nullable=False),
    sa.Column('social_connection_score', sa.SmallInteger(), nullable=False),
    sa.Column('work_stress_baseline', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age_range_max <= 120', name='ck_user_context_age_max_upper_bound'),
    sa.CheckConstraint('age_range_min <= age_range_max', name='ck_user_context_age_range_order'),
    sa.CheckConstraint('age_range_min >= 13', name='ck_user_context_age_min_lower_bound'),
    sa.CheckConstraint('family_support_score >= 0 AND family_support_score <= 10', name='ck_user_context_family_support_score_range'),
    sa.CheckConstraint('social_connection_score >= 0 AND social_connection_score <= 10', name='ck_user_context_social_connection_score_range'),
    sa.CheckConstraint('work_stress_baseline >= 0 AND work_stress_baseline <= 10', name='ck_user_context_work_stress_baseline_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_contexts_created_at'), 'user_contexts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_contexts_created_at'), table_name='user_contexts')
    op.drop_table('user_contexts')
    # ### end Alembic commands ###
