"""create journal analysis layer

Revision ID: 18a568f15c9c
Revises: 922812cf336f
Create Date: 2026-07-07 18:35:27.017421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18a568f15c9c'
down_revision: Union[str, Sequence[str], None] = '922812cf336f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('emotional_tone', sa.String(length=150), nullable=True),
    sa.Column('safety_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('life_event_candidates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed')", name='ck_journal_analyses_status'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_entry_id', name='uq_journal_analyses_journal_entry_id')
    )
    op.create_index(op.f('ix_journal_analyses_created_at'), 'journal_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_analyses_journal_entry_id'), 'journal_analyses', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_analyses_status'), 'journal_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_journal_analyses_user_id'), 'journal_analyses', ['user_id'], unique=False)
    op.create_table('journal_extracted_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('journal_analysis_id', sa.UUID(), nullable=False),
    sa.Column('signal_code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_journal_extracted_signals_confidence_range'),
    sa.CheckConstraint('value >= 0 AND value <= 1', name='ck_journal_extracted_signals_value_range'),
    sa.ForeignKeyConstraint(['journal_analysis_id'], ['journal_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_analysis_id', 'signal_code', name='uq_journal_extracted_signals_analysis_signal')
    )
    op.create_index(op.f('ix_journal_extracted_signals_created_at'), 'journal_extracted_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_extracted_signals_journal_analysis_id'), 'journal_extracted_signals', ['journal_analysis_id'], unique=False)
    op.create_index(op.f('ix_journal_extracted_signals_journal_entry_id'), 'journal_extracted_signals', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_extracted_signals_signal_code'), 'journal_extracted_signals', ['signal_code'], unique=False)
    op.create_index(op.f('ix_journal_extracted_signals_user_id'), 'journal_extracted_signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_extracted_signals_user_id'), table_name='journal_extracted_signals')
    op.drop_index(op.f('ix_journal_extracted_signals_signal_code'), table_name='journal_extracted_signals')
    op.drop_index(op.f('ix_journal_extracted_signals_journal_entry_id'), table_name='journal_extracted_signals')
    op.drop_index(op.f('ix_journal_extracted_signals_journal_analysis_id'), table_name='journal_extracted_signals')
    op.drop_index(op.f('ix_journal_extracted_signals_created_at'), table_name='journal_extracted_signals')
    op.drop_table('journal_extracted_signals')
    op.drop_index(op.f('ix_journal_analyses_user_id'), table_name='journal_analyses')
    op.drop_index(op.f('ix_journal_analyses_status'), table_name='journal_analyses')
    op.drop_index(op.f('ix_journal_analyses_journal_entry_id'), table_name='journal_analyses')
    op.drop_index(op.f('ix_journal_analyses_created_at'), table_name='journal_analyses')
    op.drop_table('journal_analyses')
    # ### end Alembic commands ###
