"""create safety events

Revision ID: 21aba7c25698
Revises: b076b85a4ad6
Create Date: 2026-07-06 18:20:01.262133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21aba7c25698'
down_revision: Union[str, Sequence[str], None] = 'b076b85a4ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("flag_type IN ('self_harm_risk', 'harm_to_others_risk', 'abuse_or_coercion_context', 'severe_distress')", name='ck_safety_event_flag_type'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_safety_event_severity'),
    sa.CheckConstraint("source_type IN ('journal_entry', 'reflection_response', 'manual')", name='ck_safety_event_source_type'),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'resolved')", name='ck_safety_event_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id', 'flag_type', name='uq_safety_event_user_source_flag')
    )
    op.create_index(op.f('ix_safety_events_created_at'), 'safety_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_safety_events_flag_type'), 'safety_events', ['flag_type'], unique=False)
    op.create_index(op.f('ix_safety_events_severity'), 'safety_events', ['severity'], unique=False)
    op.create_index(op.f('ix_safety_events_source_id'), 'safety_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_safety_events_source_type'), 'safety_events', ['source_type'], unique=False)
    op.create_index(op.f('ix_safety_events_status'), 'safety_events', ['status'], unique=False)
    op.create_index(op.f('ix_safety_events_user_id'), 'safety_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_events_user_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_status'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_source_type'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_source_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_severity'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_flag_type'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_created_at'), table_name='safety_events')
    op.drop_table('safety_events')
    # ### end Alembic commands ###
