"""create pattern detections

Revision ID: 25e28797c804
Revises: cde8b2aaa21e
Create Date: 2026-07-05 11:14:17.177089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25e28797c804'
down_revision: Union[str, Sequence[str], None] = 'cde8b2aaa21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pattern_code', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('window_start_date', sa.Date(), nullable=False),
    sa.Column('window_end_date', sa.Date(), nullable=False),
    sa.Column('detection_window_days', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_pattern_detection_confidence_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pattern_code', 'window_start_date', 'window_end_date', name='uq_pattern_detection_user_code_window')
    )
    op.create_index(op.f('ix_pattern_detections_created_at'), 'pattern_detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_pattern_detections_pattern_code'), 'pattern_detections', ['pattern_code'], unique=False)
    op.create_index(op.f('ix_pattern_detections_pattern_type'), 'pattern_detections', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_pattern_detections_severity'), 'pattern_detections', ['severity'], unique=False)
    op.create_index(op.f('ix_pattern_detections_user_id'), 'pattern_detections', ['user_id'], unique=False)
    op.create_index(op.f('ix_pattern_detections_window_end_date'), 'pattern_detections', ['window_end_date'], unique=False)
    op.create_index(op.f('ix_pattern_detections_window_start_date'), 'pattern_detections', ['window_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_detections_window_start_date'), table_name='pattern_detections')
    op.drop_index(op.f('ix_pattern_detections_window_end_date'), table_name='pattern_detections')
    op.drop_index(op.f('ix_pattern_detections_user_id'), table_name='pattern_detections')
    op.drop_index(op.f('ix_pattern_detections_severity'), table_name='pattern_detections')
    op.drop_index(op.f('ix_pattern_detections_pattern_type'), table_name='pattern_detections')
    op.drop_index(op.f('ix_pattern_detections_pattern_code'), table_name='pattern_detections')
    op.drop_index(op.f('ix_pattern_detections_created_at'), table_name='pattern_detections')
    op.drop_table('pattern_detections')
    # ### end Alembic commands ###
