"""create initial miru schema

Revision ID: 309e13ae0773
Revises: 
Create Date: 2026-07-03 20:38:07.534499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309e13ae0773'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_signal_catalog_code')
    )
    op.create_index(op.f('ix_signal_catalog_code'), 'signal_catalog', ['code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('structured_checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('stress_score', sa.Integer(), nullable=False),
    sa.Column('energy_score', sa.Integer(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=False),
    sa.Column('social_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('energy_score >= 0 AND energy_score <= 10', name='ck_energy_score_range'),
    sa.CheckConstraint('mood_score >= 0 AND mood_score <= 10', name='ck_mood_score_range'),
    sa.CheckConstraint('sleep_score >= 0 AND sleep_score <= 10', name='ck_sleep_score_range'),
    sa.CheckConstraint('social_score >= 0 AND social_score <= 10', name='ck_social_score_range'),
    sa.CheckConstraint('stress_score >= 0 AND stress_score <= 10', name='ck_stress_score_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structured_checkins_created_at'), 'structured_checkins', ['created_at'], unique=False)
    op.create_index(op.f('ix_structured_checkins_user_id'), 'structured_checkins', ['user_id'], unique=False)
    op.create_table('user_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_user_signal_confidence_range'),
    sa.CheckConstraint('value >= 0 AND value <= 1', name='ck_user_signal_value_range'),
    sa.ForeignKeyConstraint(['signal_id'], ['signal_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_signals_recorded_at'), 'user_signals', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_user_signals_signal_id'), 'user_signals', ['signal_id'], unique=False)
    op.create_index(op.f('ix_user_signals_source_id'), 'user_signals', ['source_id'], unique=False)
    op.create_index(op.f('ix_user_signals_source_type'), 'user_signals', ['source_type'], unique=False)
    op.create_index(op.f('ix_user_signals_user_id'), 'user_signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_signals_user_id'), table_name='user_signals')
    op.drop_index(op.f('ix_user_signals_source_type'), table_name='user_signals')
    op.drop_index(op.f('ix_user_signals_source_id'), table_name='user_signals')
    op.drop_index(op.f('ix_user_signals_signal_id'), table_name='user_signals')
    op.drop_index(op.f('ix_user_signals_recorded_at'), table_name='user_signals')
    op.drop_table('user_signals')
    op.drop_index(op.f('ix_structured_checkins_user_id'), table_name='structured_checkins')
    op.drop_index(op.f('ix_structured_checkins_created_at'), table_name='structured_checkins')
    op.drop_table('structured_checkins')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_signal_catalog_code'), table_name='signal_catalog')
    op.drop_table('signal_catalog')
    # ### end Alembic commands ###
