"""create user goals

Revision ID: 375a76e27ccd
Revises: 18a568f15c9c
Create Date: 2026-07-13 10:36:20.993712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375a76e27ccd'
down_revision: Union[str, Sequence[str], None] = '18a568f15c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emotional_impact', sa.SmallInteger(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_date_precision', sa.String(length=20), nullable=False),
    sa.Column('confirmation_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_event_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('family', 'relationship', 'career', 'education', 'health', 'financial', 'relocation', 'legal', 'trauma', 'achievement', 'personal_growth', 'other')", name='ck_life_events_category'),
    sa.CheckConstraint("confirmation_status IN ('candidate', 'confirmed', 'partially_confirmed', 'dismissed')", name='ck_life_events_confirmation_status'),
    sa.CheckConstraint("event_date_precision IN ('unknown', 'year', 'month', 'day', 'exact')", name='ck_life_events_event_date_precision'),
    sa.CheckConstraint("source_type IN ('manual', 'journal_analysis', 'user_registration', 'user_narrative')", name='ck_life_events_source_type'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_life_events_confidence_range'),
    sa.CheckConstraint('emotional_impact IS NULL OR (emotional_impact >= 1 AND emotional_impact <= 10)', name='ck_life_events_emotional_impact_range'),
    sa.ForeignKeyConstraint(['supersedes_event_id'], ['life_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id', 'event_type', name='uq_life_events_source_event_type')
    )
    op.create_index(op.f('ix_life_events_category'), 'life_events', ['category'], unique=False)
    op.create_index(op.f('ix_life_events_confirmation_status'), 'life_events', ['confirmation_status'], unique=False)
    op.create_index(op.f('ix_life_events_created_at'), 'life_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_life_events_detected_at'), 'life_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_life_events_emotional_impact'), 'life_events', ['emotional_impact'], unique=False)
    op.create_index(op.f('ix_life_events_event_date'), 'life_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_life_events_event_type'), 'life_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_life_events_source_id'), 'life_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_life_events_source_type'), 'life_events', ['source_type'], unique=False)
    op.create_index('ix_life_events_user_category', 'life_events', ['user_id', 'category'], unique=False)
    op.create_index('ix_life_events_user_confirmation_status', 'life_events', ['user_id', 'confirmation_status'], unique=False)
    op.create_index('ix_life_events_user_event_date', 'life_events', ['user_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_life_events_user_id'), 'life_events', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('time_horizon', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('stress_management', 'sleep', 'emotional_awareness', 'self_esteem', 'social_connection', 'work_life_balance', 'grief_processing', 'habit_building', 'personal_growth', 'mental_clarity', 'other')", name='ck_user_goals_category'),
    sa.CheckConstraint("source_type IN ('manual', 'onboarding', 'reflection_response', 'life_event', 'journal_analysis')", name='ck_user_goals_source_type'),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'archived')", name='ck_user_goals_status'),
    sa.CheckConstraint("time_horizon IN ('short_term', 'medium_term', 'long_term', 'ongoing')", name='ck_user_goals_time_horizon'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_user_goals_confidence_range'),
    sa.CheckConstraint('priority >= 1 AND priority <= 10', name='ck_user_goals_priority_range'),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name='ck_user_goals_progress_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_category'), 'user_goals', ['category'], unique=False)
    op.create_index(op.f('ix_user_goals_created_at'), 'user_goals', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_goals_priority'), 'user_goals', ['priority'], unique=False)
    op.create_index(op.f('ix_user_goals_source_id'), 'user_goals', ['source_id'], unique=False)
    op.create_index(op.f('ix_user_goals_source_type'), 'user_goals', ['source_type'], unique=False)
    op.create_index(op.f('ix_user_goals_status'), 'user_goals', ['status'], unique=False)
    op.create_index(op.f('ix_user_goals_time_horizon'), 'user_goals', ['time_horizon'], unique=False)
    op.create_index('ix_user_goals_user_category', 'user_goals', ['user_id', 'category'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_index('ix_user_goals_user_priority', 'user_goals', ['user_id', 'priority'], unique=False)
    op.create_index('ix_user_goals_user_status', 'user_goals', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_goals_user_status', table_name='user_goals')
    op.drop_index('ix_user_goals_user_priority', table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index('ix_user_goals_user_category', table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_time_horizon'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_status'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_source_type'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_source_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_priority'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_created_at'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_category'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_life_events_user_id'), table_name='life_events')
    op.drop_index('ix_life_events_user_event_date', table_name='life_events')
    op.drop_index('ix_life_events_user_confirmation_status', table_name='life_events')
    op.drop_index('ix_life_events_user_category', table_name='life_events')
    op.drop_index(op.f('ix_life_events_source_type'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_source_id'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_event_type'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_event_date'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_emotional_impact'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_detected_at'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_created_at'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_confirmation_status'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_category'), table_name='life_events')
    op.drop_table('life_events')
    # ### end Alembic commands ###
