"""create journal semantic frames

Revision ID: 3c6abe1fd0b6
Revises: 375a76e27ccd
Create Date: 2026-07-13 19:10:54.363290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c6abe1fd0b6'
down_revision: Union[str, Sequence[str], None] = '375a76e27ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_semantic_frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('journal_analysis_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('core_dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('emotion_labels_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semantic_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('life_domains_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('needs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('additional_dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_candidates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('raw_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_confidence IS NULL OR (overall_confidence >= 0 AND overall_confidence <= 1)', name='ck_journal_semantic_frames_overall_confidence_range'),
    sa.ForeignKeyConstraint(['journal_analysis_id'], ['journal_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_analysis_id', name='uq_journal_semantic_frames_journal_analysis_id')
    )
    op.create_index(op.f('ix_journal_semantic_frames_created_at'), 'journal_semantic_frames', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_semantic_frames_journal_analysis_id'), 'journal_semantic_frames', ['journal_analysis_id'], unique=False)
    op.create_index(op.f('ix_journal_semantic_frames_journal_entry_id'), 'journal_semantic_frames', ['journal_entry_id'], unique=False)
    op.create_index('ix_journal_semantic_frames_life_domains_gin', 'journal_semantic_frames', ['life_domains_json'], unique=False, postgresql_using='gin')
    op.create_index('ix_journal_semantic_frames_needs_gin', 'journal_semantic_frames', ['needs_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_journal_semantic_frames_provider'), 'journal_semantic_frames', ['provider'], unique=False)
    op.create_index('ix_journal_semantic_frames_semantic_tags_gin', 'journal_semantic_frames', ['semantic_tags_json'], unique=False, postgresql_using='gin')
    op.create_index('ix_journal_semantic_frames_user_created', 'journal_semantic_frames', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_journal_semantic_frames_user_id'), 'journal_semantic_frames', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_semantic_frames_user_id'), table_name='journal_semantic_frames')
    op.drop_index('ix_journal_semantic_frames_user_created', table_name='journal_semantic_frames')
    op.drop_index('ix_journal_semantic_frames_semantic_tags_gin', table_name='journal_semantic_frames', postgresql_using='gin')
    op.drop_index(op.f('ix_journal_semantic_frames_provider'), table_name='journal_semantic_frames')
    op.drop_index('ix_journal_semantic_frames_needs_gin', table_name='journal_semantic_frames', postgresql_using='gin')
    op.drop_index('ix_journal_semantic_frames_life_domains_gin', table_name='journal_semantic_frames', postgresql_using='gin')
    op.drop_index(op.f('ix_journal_semantic_frames_journal_entry_id'), table_name='journal_semantic_frames')
    op.drop_index(op.f('ix_journal_semantic_frames_journal_analysis_id'), table_name='journal_semantic_frames')
    op.drop_index(op.f('ix_journal_semantic_frames_created_at'), table_name='journal_semantic_frames')
    op.drop_table('journal_semantic_frames')
    # ### end Alembic commands ###
