"""create current emotional states

Revision ID: 4816b989a845
Revises: 309e13ae0773
Create Date: 2026-07-04 00:16:51.424087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4816b989a845'
down_revision: Union[str, Sequence[str], None] = '309e13ae0773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_emotional_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stress_level', sa.Float(), nullable=True),
    sa.Column('energy_level', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Float(), nullable=True),
    sa.Column('social_connection', sa.Float(), nullable=True),
    sa.Column('emotional_stability', sa.Float(), nullable=True),
    sa.Column('motivation', sa.Float(), nullable=True),
    sa.Column('self_esteem', sa.Float(), nullable=True),
    sa.Column('physical_activity', sa.Float(), nullable=True),
    sa.Column('eating_habits', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_state_confidence_range'),
    sa.CheckConstraint('eating_habits IS NULL OR (eating_habits >= 0 AND eating_habits <= 1)', name='ck_state_eating_habits_range'),
    sa.CheckConstraint('emotional_stability IS NULL OR (emotional_stability >= 0 AND emotional_stability <= 1)', name='ck_state_emotional_stability_range'),
    sa.CheckConstraint('energy_level IS NULL OR (energy_level >= 0 AND energy_level <= 1)', name='ck_state_energy_range'),
    sa.CheckConstraint('motivation IS NULL OR (motivation >= 0 AND motivation <= 1)', name='ck_state_motivation_range'),
    sa.CheckConstraint('physical_activity IS NULL OR (physical_activity >= 0 AND physical_activity <= 1)', name='ck_state_physical_activity_range'),
    sa.CheckConstraint('self_esteem IS NULL OR (self_esteem >= 0 AND self_esteem <= 1)', name='ck_state_self_esteem_range'),
    sa.CheckConstraint('sleep_quality IS NULL OR (sleep_quality >= 0 AND sleep_quality <= 1)', name='ck_state_sleep_range'),
    sa.CheckConstraint('social_connection IS NULL OR (social_connection >= 0 AND social_connection <= 1)', name='ck_state_social_range'),
    sa.CheckConstraint('stress_level IS NULL OR (stress_level >= 0 AND stress_level <= 1)', name='ck_state_stress_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_emotional_states_calculated_at'), 'current_emotional_states', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_current_emotional_states_user_id'), 'current_emotional_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_emotional_states_user_id'), table_name='current_emotional_states')
    op.drop_index(op.f('ix_current_emotional_states_calculated_at'), table_name='current_emotional_states')
    op.drop_table('current_emotional_states')
    # ### end Alembic commands ###
