"""create daily reflections

Revision ID: 4fea4d6e5553
Revises: 113701065477
Create Date: 2026-07-05 14:20:05.800430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fea4d6e5553'
down_revision: Union[str, Sequence[str], None] = '113701065477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reflections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reflection_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('emotional_state_summary', sa.Text(), nullable=True),
    sa.Column('insight_summary', sa.Text(), nullable=True),
    sa.Column('pattern_summary', sa.Text(), nullable=True),
    sa.Column('action_summary', sa.Text(), nullable=True),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reflection_date', name='uq_daily_reflection_user_date')
    )
    op.create_index(op.f('ix_daily_reflections_created_at'), 'daily_reflections', ['created_at'], unique=False)
    op.create_index(op.f('ix_daily_reflections_reflection_date'), 'daily_reflections', ['reflection_date'], unique=False)
    op.create_index(op.f('ix_daily_reflections_user_id'), 'daily_reflections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_reflections_user_id'), table_name='daily_reflections')
    op.drop_index(op.f('ix_daily_reflections_reflection_date'), table_name='daily_reflections')
    op.drop_index(op.f('ix_daily_reflections_created_at'), table_name='daily_reflections')
    op.drop_table('daily_reflections')
    # ### end Alembic commands ###
