"""create basic insights

Revision ID: 9c34dcb6c6ff
Revises: 3473f6182b00
Create Date: 2026-07-04 12:58:55.221615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c34dcb6c6ff'
down_revision: Union[str, Sequence[str], None] = '3473f6182b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_basic_insight_confidence_range'),
    sa.ForeignKeyConstraint(['state_id'], ['current_emotional_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'rule_code', name='uq_basic_insight_state_rule')
    )
    op.create_index(op.f('ix_basic_insights_created_at'), 'basic_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_basic_insights_rule_code'), 'basic_insights', ['rule_code'], unique=False)
    op.create_index(op.f('ix_basic_insights_state_id'), 'basic_insights', ['state_id'], unique=False)
    op.create_index(op.f('ix_basic_insights_user_id'), 'basic_insights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basic_insights_user_id'), table_name='basic_insights')
    op.drop_index(op.f('ix_basic_insights_state_id'), table_name='basic_insights')
    op.drop_index(op.f('ix_basic_insights_rule_code'), table_name='basic_insights')
    op.drop_index(op.f('ix_basic_insights_created_at'), table_name='basic_insights')
    op.drop_table('basic_insights')
    # ### end Alembic commands ###
