"""create reflection responses

Revision ID: b076b85a4ad6
Revises: e357a967b987
Create Date: 2026-07-06 08:57:24.024627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b076b85a4ad6'
down_revision: Union[str, Sequence[str], None] = 'e357a967b987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflection_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('response_type', sa.String(length=100), nullable=False),
    sa.Column('suggested_action_id', sa.UUID(), nullable=True),
    sa.Column('source_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("response_type IN ('supportive_reflection', 'action_oriented', 'summary', 'gentle_checkin')", name='ck_reflection_response_type'),
    sa.CheckConstraint("source_type IN ('current_emotional_state', 'daily_reflection', 'journal_entry', 'manual')", name='ck_reflection_response_source_type'),
    sa.CheckConstraint("tone IN ('balanced', 'direct', 'gentle', 'detailed')", name='ck_reflection_response_tone'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(
        "ck_user_feedback_target_type",
        "user_feedback",
        type_="check",
    )
    op.create_check_constraint(
        "ck_user_feedback_target_type",
        "user_feedback",
        "target_type IN ('basic_insight', 'action_suggestion', 'daily_reflection', 'pattern_detection', 'reflection_response')",
    )
    op.create_index(op.f('ix_reflection_responses_created_at'), 'reflection_responses', ['created_at'], unique=False)
    op.create_index(op.f('ix_reflection_responses_response_type'), 'reflection_responses', ['response_type'], unique=False)
    op.create_index(op.f('ix_reflection_responses_source_id'), 'reflection_responses', ['source_id'], unique=False)
    op.create_index(op.f('ix_reflection_responses_source_type'), 'reflection_responses', ['source_type'], unique=False)
    op.create_index(op.f('ix_reflection_responses_suggested_action_id'), 'reflection_responses', ['suggested_action_id'], unique=False)
    op.create_index(op.f('ix_reflection_responses_user_id'), 'reflection_responses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    #### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_user_feedback_target_type",
        "user_feedback",
        type_="check",
    )
    op.create_check_constraint(
        "ck_user_feedback_target_type",
        "user_feedback",
        "target_type IN ('basic_insight', 'action_suggestion', 'daily_reflection', 'pattern_detection')",
    )
    op.drop_index(op.f('ix_reflection_responses_user_id'), table_name='reflection_responses')
    op.drop_index(op.f('ix_reflection_responses_suggested_action_id'), table_name='reflection_responses')
    op.drop_index(op.f('ix_reflection_responses_source_type'), table_name='reflection_responses')
    op.drop_index(op.f('ix_reflection_responses_source_id'), table_name='reflection_responses')
    op.drop_index(op.f('ix_reflection_responses_response_type'), table_name='reflection_responses')
    op.drop_index(op.f('ix_reflection_responses_created_at'), table_name='reflection_responses')
    op.drop_table('reflection_responses')
    # ### end Alembic commands ###
