"""create llm runs

Revision ID: cde8b2aaa21e
Revises: 9c34dcb6c6ff
Create Date: 2026-07-04 22:11:06.331599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cde8b2aaa21e'
down_revision: Union[str, Sequence[str], None] = '9c34dcb6c6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed')", name='ck_llm_run_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_runs_created_at'), 'llm_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_runs_provider'), 'llm_runs', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_runs_source_id'), 'llm_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_llm_runs_source_type'), 'llm_runs', ['source_type'], unique=False)
    op.create_index(op.f('ix_llm_runs_status'), 'llm_runs', ['status'], unique=False)
    op.create_index(op.f('ix_llm_runs_user_id'), 'llm_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_runs_user_id'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_status'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_source_type'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_source_id'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_provider'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_created_at'), table_name='llm_runs')
    op.drop_table('llm_runs')
    # ### end Alembic commands ###
