"""create user feedback

Revision ID: e357a967b987
Revises: 5f1c55ab2ee3
Create Date: 2026-07-05 17:44:28.424270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e357a967b987'
down_revision: Union[str, Sequence[str], None] = '5f1c55ab2ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rating IN ('useful', 'not_useful', 'inaccurate', 'too_direct', 'too_vague', 'not_relevant')", name='ck_user_feedback_rating'),
    sa.CheckConstraint("target_type IN ('basic_insight', 'action_suggestion', 'daily_reflection', 'pattern_detection')", name='ck_user_feedback_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_user_feedback_user_target')
    )
    op.create_index(op.f('ix_user_feedback_created_at'), 'user_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_feedback_rating'), 'user_feedback', ['rating'], unique=False)
    op.create_index(op.f('ix_user_feedback_target_id'), 'user_feedback', ['target_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_target_type'), 'user_feedback', ['target_type'], unique=False)
    op.create_index(op.f('ix_user_feedback_user_id'), 'user_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedback_user_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_target_type'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_target_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_rating'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_created_at'), table_name='user_feedback')
    op.drop_table('user_feedback')
    # ### end Alembic commands ###
